"""Coordinate interchangeable discovery, mapping, hydration and static rendering."""
from __future__ import annotations

from dataclasses import asdict, dataclass, replace
import json
from pathlib import Path
import re
import tempfile
import shutil
import shlex
from typing import Callable

from heckle.config import Connection
from heckle.core.inventory import load_inventory, save_inventory
from heckle.core.model import ForgeModel, Source
from heckle.core.registry import backend
from heckle.core.security import check_destination, publish, write_private_json
from heckle.compatibility import audited, compatibility_warnings
from heckle.errors import GenerationError, UnsafeAdoptionError
from heckle.opentofu import TfRunner
from heckle.reporting import generation_report


@dataclass(frozen=True)
class Options:
    output: Path
    force: bool = False
    allow_partial: bool = False
    prevent_destroy: bool = True
    split_teams: bool = False
    keep_inventory: bool = False
    validate: bool = True
    tf: str | None = None
    from_inventory: Path | None = None
    state_root: Path | None = None
    provider_version: str | None = None
    allow_untested_provider: bool = False
    keep_workdir: bool = False


GENERATED_README = """# {forge} infrastructure: {scope}

Generated by Heckle. This is a normal Terraform/OpenTofu project: Heckle, Python, inventory
JSON and generation workers are **not** needed for its ongoing use.

The provider version and original forge host/scope are pinned. Add your own backend
configuration, provide provider credentials using `{token}`, and supply any
required sensitive variables declared in `variables.tf`. Existing webhook URLs
are private inputs rather than committed defaults. Variables can have structured
values when the provider models a webhook configuration as a map.

```sh
{tf} init
{tf} plan -out=import.tfplan
{tf} show import.tfplan
# Only after reviewing the entire plan:
{tf} apply import.tfplan
{tf} plan
```

Heckle never runs the apply command above. For a fresh adoption, Heckle rehearses
the final adoption path privately. A provider handler may recognise narrowly-defined,
version-scoped provider behaviour under explicit guard conditions; create/delete/replace
and unrecognised updates still fail. Recognition is descriptive, not a recommendation
to apply a plan. Heckle cannot guarantee that a generated or reconciled plan is safe,
complete, or free from unintended changes. Review every saved plan yourself. The decision
to apply a plan, and responsibility for resulting changes, remains with the operator.
Protect state and saved plans as confidential data.

Edit the ordinary `.tf` data files and `modules/` directly after adoption. Do not
rerun the generator over an adopted project. Retained import blocks are ordinary
Terraform/OpenTofu declarations; no separate import worker is needed.

## Coverage and safety

Inspect `.generation/report.json`: inventory-only, unsupported, non-importable and
permission-denied objects are not silently converted into create operations.
Archived repositories are inventoried but excluded from configuration generation.
The report covers queried endpoints, not every possible setting on the forge.

`prevent_destroy` is enabled by default on native resource modules and GitHub
repositories. It is not protection after removing an entire resource/module block,
and it does not prevent in-place changes or creation of a missing remote object.
Gitea's team-members resource manages an authoritative membership set; review
removals carefully and deliberately change lifecycle policy for replacements.

For GitHub secret metadata, the retained adapter uses provider-required placeholder
values with `ignore_changes` during import and updates. **Never use those resources
to create or restore a secret without replacing the placeholder with a real value.**
GitLab/Gitea/Forgejo CI secret and variable values are not exported into HCL.

Private inventory is retained only with `--keep-inventory`; delete it when no
longer needed. Keep `.terraform.lock.hcl` to retain provider checksums. Nothing
under `.generation/` is needed by Terraform or OpenTofu.
"""


def reconcile_existing_state(project, existing_state: set[str]) -> None:
    """Map an existing Heckle state onto the current generated addresses.

    Native presence profiles can move an instance from the historical
    ``.this[key]`` address to a profile-specific resource block.  Existing
    state must be renamed with a moved block rather than importing the same
    remote object a second time.
    """
    project.skip_imports = set(existing_state)
    for item in project.resources:
        legacy = item.candidate.address
        current = item.address
        if legacy == current:
            continue
        if legacy in existing_state and current in existing_state:
            raise GenerationError(
                f"State contains both legacy and current addresses for {item.candidate.key}; "
                "refusing to guess which state object should be kept"
            )
        if legacy in existing_state:
            project.skip_imports.add(current)
            project.moved.append((legacy, current))


def write_state_only_adopt_script(
    path: Path,
    imports: list[tuple[str, str]],
    known_provider_behaviour_changes: list[dict[str, object]] | None = None,
    *,
    tf_command: str = "tofu",
    tf_label: str = "OpenTofu",
) -> None:
    """Write a one-time, resumable state-only adoption helper.

    If the provider has version-scoped behaviour recognised by Heckle, the helper accepts
    only the exact rehearsed address/attribute set while its guard conditions remain
    unchanged. Recognition is descriptive only; the helper never treats an arbitrary
    plan exit code 2 as success.
    """
    commands = "\n".join(
        f"import_one {shlex.quote(address)} {shlex.quote(import_id)}"
        for address, import_id in imports
    )
    expected = {
        str(item["address"]): {
            "attributes": list(item.get("attributes", [])),
            "guards": dict(item.get("guards", {})),
        }
        for item in (known_provider_behaviour_changes or [])
    }
    expected_shell = shlex.quote(json.dumps(expected, sort_keys=True))
    tf_selector = '${HECKLE_TF_BIN:-' + shlex.quote(tf_command) + '}'
    header = f"""#!/usr/bin/env bash
set -euo pipefail

TF={tf_selector}
TF_LABEL={shlex.quote(tf_label)}
EXPECTED_PROVIDER_BEHAVIOUR={expected_shell}
"$TF" init
CURRENT_STATE="$("$TF" state list 2>/dev/null || true)"

import_one() {{
  local address="$1" import_id="$2"
  if printf '%s\\n' "$CURRENT_STATE" | grep -Fqx -- "$address"; then
    printf 'Already in state: %s\\n' "$address"
    return 0
  fi
  printf 'Importing into state only: %s\\n' "$address"
  "$TF" import -input=false "$address" "$import_id"
  CURRENT_STATE="${{CURRENT_STATE}}${{CURRENT_STATE:+$'\\n'}}${{address}}"
}}

"""
    footer = r"""

printf '%s\n' "All requested objects are now in $TF_LABEL state."
printf '%s\n' "Checking the managed configuration..."
set +e
"$TF" plan -detailed-exitcode -out=adoption.tfplan
status=$?
set -e
case $status in
  0)
    printf '%s\n' "Adoption complete: the follow-up plan has no changes."
    printf '%s\n' "You may remove adopt.sh and adoption.tfplan after review."
    ;;
  2)
    if [ "$EXPECTED_PROVIDER_BEHAVIOUR" = "{}" ]; then
      printf '%s\n' "The follow-up plan contains changes. DO NOT APPLY IT." >&2
      printf '%s\n' "Inspect it with: $TF show adoption.tfplan" >&2
      exit 2
    fi
    plan_json=".heckle-adoption-plan.json"
    "$TF" show -json adoption.tfplan > "$plan_json"
    set +e
    EXPECTED_PROVIDER_BEHAVIOUR="$EXPECTED_PROVIDER_BEHAVIOUR" python3 - "$plan_json" <<'HECKLE_PY'
import json
import os
import sys


def changed_paths(before, after, unknown, prefix=""):
    if unknown is True:
        return []
    if isinstance(before, dict) or isinstance(after, dict):
        left = before if isinstance(before, dict) else {}
        right = after if isinstance(after, dict) else {}
        unknown_map = unknown if isinstance(unknown, dict) else {}
        output = []
        for key in sorted(set(left) | set(right)):
            child = f"{prefix}.{key}" if prefix else str(key)
            output.extend(changed_paths(left.get(key), right.get(key), unknown_map.get(key), child))
        return output
    if isinstance(before, list) or isinstance(after, list):
        left = before if isinstance(before, list) else []
        right = after if isinstance(after, list) else []
        unknown_list = unknown if isinstance(unknown, list) else []
        output = []
        for index in range(max(len(left), len(right))):
            child = f"{prefix}[{index}]"
            output.extend(changed_paths(
                left[index] if index < len(left) else None,
                right[index] if index < len(right) else None,
                unknown_list[index] if index < len(unknown_list) else None,
                child,
            ))
        return output
    return [prefix or "<root>"] if before != after else []


with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)
expected = json.loads(os.environ["EXPECTED_PROVIDER_BEHAVIOUR"])
problems = []
accepted = []
for resource in payload.get("resource_changes", []):
    if resource.get("mode") != "managed":
        continue
    detail = resource.get("change") or {}
    actions = detail.get("actions") or []
    if actions == ["no-op"]:
        continue
    address = resource.get("address", "<unknown>")
    rule = expected.get(address)
    if actions != ["update"] or rule is None:
        problems.append(f"{address}: unexpected actions {actions}")
        continue
    actual = set(changed_paths(detail.get("before"), detail.get("after"), detail.get("after_unknown")))
    allowed = set(rule.get("attributes", []))
    extra = sorted(actual - allowed)
    if extra:
        problems.append(f"{address}: unexpected attributes {', '.join(extra)}")
        continue
    before = detail.get("before") if isinstance(detail.get("before"), dict) else {}
    after = detail.get("after") if isinstance(detail.get("after"), dict) else {}
    bad_guards = [
        name for name, value in (rule.get("guards") or {}).items()
        if before.get(name) != value or after.get(name) != value
    ]
    if bad_guards:
        problems.append(f"{address}: controlling feature changed: {', '.join(sorted(bad_guards))}")
        continue
    accepted.append((address, sorted(actual)))

if problems:
    for problem in problems:
        print(problem, file=sys.stderr)
    raise SystemExit(2)
if not accepted:
    print("Plan exit code indicated changes but none matched Heckle's rehearsed known provider behaviour.", file=sys.stderr)
    raise SystemExit(2)
for address, attributes in accepted:
    print(f"Known provider behaviour: {address}: {', '.join(attributes)}")
HECKLE_PY
    check_status=$?
    set -e
    rm -f "$plan_json"
    if [ "$check_status" -ne 0 ]; then
      printf '%s\n' "The follow-up plan contains changes outside Heckle's known provider-behaviour rules. DO NOT APPLY IT." >&2
      printf '%s\n' "Inspect it with: $TF show adoption.tfplan" >&2
      exit 2
    fi
    printf '%s\n' "Adoption complete."
    printf '%s\n' "The follow-up plan contains only differences that Heckle recognises as known provider behaviour under specific parent-feature settings."
    printf '%s\n' "These differences may be safe to reconcile because the affected settings are not currently active, but Heckle cannot determine whether applying them is appropriate for your environment."
    printf '%s\n' "Review the plan and the provider's behaviour carefully before deciding whether to apply it."
    printf '%s\n' "If you choose to reconcile the differences: $TF apply adoption.tfplan"
    printf '%s\n' "Then verify the result with: $TF plan"
    printf '%s\n' "Applying the plan is your decision and may modify remote resources."
    printf '%s\n' "You may remove adopt.sh after review."
    ;;
  *)
    printf '%s plan failed with exit status %s.\n' "$TF_LABEL" "$status" >&2
    exit "$status"
    ;;
esac
"""
    path.write_text(header + commands + footer, encoding="utf-8")
    path.chmod(0o755)


class Pipeline:
    def __init__(self, connection: Connection, options: Options, *, runner: TfRunner | None = None,
                 forge: object | None = None, progress: Callable[[str], None] = print) -> None:
        self.connection = connection
        self.options = options
        registration = backend(connection.source.forge)
        self.forge = forge or registration.forge(connection)
        self.provider = registration.provider()
        if options.provider_version:
            if not re.fullmatch(r"\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?", options.provider_version):
                raise GenerationError("--provider-version must be an exact semantic version")
            self.provider.spec = replace(self.provider.spec, version=options.provider_version)
        if not audited(self.provider.spec) and not options.allow_untested_provider:
            raise GenerationError(
                f"Provider {self.provider.spec.source} {self.provider.spec.version} has not been "
                "audited by this Heckle release. Use the pinned version or explicitly pass "
                "--allow-untested-provider for experimental use."
            )
        self.runner = runner
        self.progress = progress

    def discover(self, workspace: Path) -> ForgeModel:
        if self.options.from_inventory:
            self.progress("Loading the saved inventory (provider hydration still contacts the forge).")
            model = load_inventory(self.options.from_inventory)
            if not self.connection.source.resolved:
                self.forge.resolve_source()
                self.connection = self.forge.connection
            if not model.source.matches(self.connection.source):
                raise GenerationError("Snapshot forge, host, namespace type and scope must exactly match the requested source")
            self.connection = replace(self.connection, source=model.source)
            return model
        self.progress(f"Discovering {self.connection.source.forge} configuration for {self.connection.source.scope}.")
        model = self.forge.discover(workspace)
        if self.connection.source.resolved and not self.connection.source.matches(model.source):
            raise GenerationError("Discovered source does not match the requested namespace")
        self.connection = replace(self.connection, source=model.source)
        return model

    def _diagnostic_workdir_message(self, work: Path) -> None:
        self.progress(f"Temporary workspace retained for diagnostics: {work}")
        command = getattr(self.runner, "project_command", "tofu")
        failed_cwd = getattr(self.runner, "last_cwd", None)
        failed_args = getattr(self.runner, "last_arguments", None)
        if failed_cwd is not None and failed_args:
            failed_cwd = Path(failed_cwd)
            try:
                failed_cwd.relative_to(work)
            except ValueError:
                pass
            else:
                rendered = shlex.join([str(command), *map(str, failed_args)])
                init_hint = ""
                if str(failed_args[0]) == "plan":
                    init_hint = (
                        f"  {shlex.quote(str(command))} init -backend=false -input=false -no-color\n"
                    )
                self.progress(
                    "The failing command was:\n"
                    f"  cd {shlex.quote(str(failed_cwd))}\n"
                    f"{init_hint}"
                    f"  {rendered}\n"
                    "Re-run these commands there to see the CLI/provider diagnostics privately."
                )
                return
        result = work / "result"
        if not result.is_dir():
            return
        quoted_command = shlex.quote(str(command))
        self.progress(
            "To inspect diagnostics privately, run:\n"
            f"  cd {shlex.quote(str(result))}\n"
            f"  {quoted_command} init -backend=false -input=false -no-color\n"
            f"  {quoted_command} validate -no-color"
        )

    def run(self, *, inventory_only: bool = False) -> Path:
        destination = check_destination(self.options.output, force=self.options.force)
        destination.parent.mkdir(parents=True, exist_ok=True)
        work = Path(tempfile.mkdtemp(prefix=f".{destination.name}-build-", dir=destination.parent))
        work.chmod(0o700)
        retain_work = False
        try:
            if not inventory_only:
                self.runner = self.runner or TfRunner(self.options.tf, self.connection)
                self.progress("Checking Terraform/OpenTofu version before discovery.")
                self.runner.check_version(work)
            model = self.discover(work)
            plan = self.provider.plan(model, work)
            for warning in compatibility_warnings(self.provider.spec):
                if warning not in plan.coverage.warnings:
                    plan.coverage.warnings.append(warning)
            output = work / "result"
            if inventory_only:
                save_inventory(output, model)
                write_private_json(output / "report.json", generation_report(plan, self.provider.spec))
                publish(output, destination, force=self.options.force)
                return destination
            failures = [o for o in model.observations if o.status in {"permission_denied", "failed"}]
            if failures and not self.options.allow_partial:
                raise GenerationError(f"Discovery has {len(failures)} permission/API failure(s). Run inventory and inspect coverage, then fix credentials or explicitly use --allow-partial.")
            # Discovery can resolve --me or canonicalise the namespace.
            self.runner.connection = self.connection
            self.progress(
                "Bootstrapping provider installation and schema loading; only provider.tf "
                "and versions.tf are expected initially. Resource HCL follows hydration."
            )
            self.progress(f"Hydrating {len(plan.candidates)} import candidates using {self.provider.spec.source} {self.provider.spec.version}.")
            resources, schema = self.runner.hydrate(self.provider, plan, work / "bootstrap")
            project = self.provider.compile(plan, resources, schema)
            if self.options.state_root:
                root = self.options.state_root.expanduser().resolve()
                source_file = root / ".generation" / "source.json"
                try:
                    state_source = json.loads(source_file.read_text(encoding="utf-8"))
                except (OSError, ValueError) as exc:
                    raise GenerationError("--state-root must contain Heckle's .generation/source.json identity record; do not guess an unrelated state") from exc
                if not Source(**state_source).matches(model.source):
                    raise GenerationError("State root is associated with a different forge, host or scope")
                existing_state = self.runner.state_addresses(root)
                reconcile_existing_state(project, existing_state)
            addresses = {r.address for r in project.resources}
            if project.native is not None:
                addresses.update(record.new_address for record in project.native.imports)
            self.progress("Rendering standalone HCL and local modules.")
            self.provider.render(project, output, prevent_destroy=self.options.prevent_destroy, split_teams=self.options.split_teams)
            self.runner.format(output)
            if self.options.validate:
                self.progress("Validating the generated project without configuring a backend.")
                self.runner.validate(output, disposable=True)
            adoption_safety: dict[str, object]
            if self.options.state_root is None:
                self.progress("Checking the configuration-driven import plan for live changes.")
                declarative_changes: list[dict[str, object]] = []
                fallback_reason: str | None = None
                try:
                    adoption_safety = self.runner.adoption_check(
                        output,
                        project.validation_inputs,
                        disposable=True,
                        known_behaviour=self.provider.known_provider_behaviour,
                    )
                    recognised = list(adoption_safety.get("known_provider_behaviour_changes", []))
                    if recognised:
                        declarative_changes = recognised
                        fallback_reason = "known provider behaviour"
                        self.progress(
                            "Declarative imports contain changes matching known provider behaviour; "
                            "rehearsing state-only adoption instead."
                        )
                    else:
                        adoption_safety["status"] = "passed_declarative_import"
                        adoption_safety["mode"] = "import_blocks"
                except UnsafeAdoptionError as declarative_error:
                    declarative_changes = [
                        {
                            "address": change.address,
                            "actions": list(change.actions),
                            "attributes": list(change.attributes),
                        }
                        for change in declarative_error.changes
                    ]
                    fallback_reason = "configuration-driven imports would change live settings"
                    self.progress(
                        "Declarative imports would change live settings; rehearsing "
                        "state-only adoption instead."
                    )

                if fallback_reason is not None:
                    imports = self.provider.rendered_imports(project)
                    imports_path = output / "imports.tf"
                    imports_path.unlink(missing_ok=True)
                    adoption_safety = self.runner.state_only_adoption_check(
                        output,
                        imports,
                        project.validation_inputs,
                        disposable=True,
                        known_behaviour=self.provider.known_provider_behaviour,
                    )
                    recognised_state = list(adoption_safety.get("known_provider_behaviour_changes", []))
                    if recognised_state:
                        self.progress(
                            f"State-only adoption found {len(recognised_state)} change(s) matching known "
                            "provider behaviour; no unrecognised changes were found."
                        )
                    adoption_safety["status"] = (
                        "passed_state_only_import_with_known_provider_behaviour"
                        if recognised_state
                        else "passed_state_only_import"
                    )
                    adoption_safety["mode"] = "state_only_import"
                    adoption_safety["fallback_reason"] = fallback_reason
                    adoption_safety["declarative_changes"] = declarative_changes
                    write_state_only_adopt_script(
                        output / "adopt.sh",
                        imports,
                        recognised_state,
                        tf_command=getattr(self.runner, "project_command", "tofu"),
                        tf_label=getattr(self.runner, "tool_name", "OpenTofu"),
                    )
            else:
                # A detached generated directory has no copy of the caller's managed
                # state, so a fresh-import safety plan would incorrectly see already
                # managed resources as creates. The user's state-root workflow is
                # intentionally validated in that managed root instead.
                adoption_safety = {"status": "skipped_existing_state", "mode": "existing_state"}
            report = generation_report(plan, self.provider.spec, generated=True, validated=self.options.validate,
                                       imported_addresses=len(addresses & project.skip_imports), project=project)
            report["partial_generation_allowed"] = self.options.allow_partial
            report["adoption_safety"] = adoption_safety
            audit = output / ".generation"
            write_private_json(audit / "report.json", report)
            write_private_json(audit / "source.json", asdict(model.source))
            if adoption_safety.get("mode") == "state_only_import":
                write_private_json(
                    audit / "imports.json",
                    [{"address": address, "id": import_id} for address, import_id in self.provider.rendered_imports(project)],
                )
            if self.options.keep_inventory:
                save_inventory(audit / "inventory", model)
            (output / ".heckle-generated").write_text("Disposable generation; remove this marker when adopting the project.\n", encoding="utf-8")
            (output / ".gitignore").write_text(".terraform/\n*.tfstate\n*.tfstate.*\n*.tfplan\n*.tfvars\n*.tfvars.json\ncrash.log\n.generation/\n", encoding="utf-8")
            readme = GENERATED_README.format(
                forge=model.source.forge,
                scope=model.source.scope,
                token=self.provider.spec.token_environment,
                tf=shlex.quote(getattr(self.runner, "project_command", "tofu")),
            )
            if model.source.forge == "forgejo":
                from heckle.providers.forgejo.repository import PERSONAL_CREATION_WARNING
                readme += (
                    "\n## Forgejo repository settings\n\n"
                    "Heckle leaves out repository creation/migration options, mirror settings and "
                    "options this provider cannot read. It does not enable pull requests or wikis "
                    "on repositories where they are disabled. Review the plan before applying it; "
                    "these exclusions are also listed in `.generation/report.json`.\n"
                )
                if model.source.namespace_type == "user":
                    readme += "\n" + PERSONAL_CREATION_WARNING + "\n"
            if adoption_safety.get("mode") == "state_only_import":
                normal_flow = (
                    f"{shlex.quote(getattr(self.runner, 'project_command', 'tofu'))} init\n"
                    f"{shlex.quote(getattr(self.runner, 'project_command', 'tofu'))} plan -out=import.tfplan\n"
                    f"{shlex.quote(getattr(self.runner, 'project_command', 'tofu'))} show import.tfplan\n"
                    "# Only after reviewing the entire plan:\n"
                    f"{shlex.quote(getattr(self.runner, 'project_command', 'tofu'))} apply import.tfplan\n"
                    f"{shlex.quote(getattr(self.runner, 'project_command', 'tofu'))} plan"
                )
                readme = readme.replace(
                    normal_flow,
                    "# Add/configure your backend first if required, then:\n./adopt.sh\n"
                    "# adopt.sh performs state-only imports and verifies the exact known\n"
                    "# provider behaviour Heckle rehearsed. It never runs apply.",
                )
                readme = readme.replace(
                    "Retained import blocks are ordinary\nTerraform/OpenTofu declarations; no separate import worker is needed.",
                    "This provider could not safely use configuration-driven import blocks, so\n`adopt.sh` is a one-time state-only adoption helper. Remove it after successful\nadoption; Heckle is not needed for ongoing use.",
                )
            recognised = list(adoption_safety.get("known_provider_behaviour_changes", []))
            if recognised:
                readme += "\n## Known provider behaviour\n\n"
                readme += (
                    "The pinned provider can produce the following plan differences under specific "
                    "parent-feature settings. Heckle recognised the attribute names under its "
                    "version-scoped compatibility rules; values are intentionally omitted. This "
                    "classification does not establish that applying the plan is safe or appropriate "
                    "for your environment. Review the plan and provider behaviour yourself before "
                    "deciding whether to apply it. Applying a plan may modify remote resources.\n\n"
                )
                for item in recognised:
                    attrs = ", ".join(str(value) for value in item.get("attributes", []))
                    reason = str(item.get("reason", "known provider behaviour"))
                    readme += f"- `{item.get('address', '<unknown>')}` — {reason}: {attrs}\n"
            (output / "README.md").write_text(readme, encoding="utf-8")
            output.chmod(0o700)
            publish(output, destination, force=self.options.force)
            return destination
        except BaseException:
            if self.options.keep_workdir:
                retain_work = True
                self._diagnostic_workdir_message(work)
            raise
        finally:
            if not retain_work:
                shutil.rmtree(work, ignore_errors=True)
